# Makefile.in generated by automake 1.14.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Make cantools.					-*-Makefile-*-

# Copyright (C) 2007-2016 Andreas Heitmann

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.




am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/cantools
pkgincludedir = $(includedir)/cantools
pkglibdir = $(libdir)/cantools
pkglibexecdir = $(libexecdir)/cantools
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-cygwin
host_triplet = x86_64-unknown-cygwin
bin_PROGRAMS = dbccopy$(EXEEXT) dbcls$(EXEEXT) cantomat$(EXEEXT) \
	mdftomat$(EXEEXT) matdump$(EXEEXT)
subdir = .
DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) \
	$(srcdir)/config.h.in src/libcandbc/parser.h \
	src/libcandbc/parser.c src/libcandbc/lexer.c strndup.c \
	realloc.c strtok_r.c strnlen.c malloc.c strtod.c depcomp \
	ylwrap $(include_HEADERS) AUTHORS COPYING ChangeLog README \
	TODO compile config.guess config.sub install-sh missing \
	ltmain.sh
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" \
	"$(DESTDIR)$(includedir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
libcanasc_la_LIBADD =
am__dirstamp = $(am__leading_dot)dirstamp
am_libcanasc_la_OBJECTS = src/libcanasc/libcanasc_la-ascReader.lo
libcanasc_la_OBJECTS = $(am_libcanasc_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
libcanasc_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libcanasc_la_LDFLAGS) $(LDFLAGS) -o $@
libcanclg_la_LIBADD =
am_libcanclg_la_OBJECTS = src/libcanclg/libcanclg_la-clgReader.lo
libcanclg_la_OBJECTS = $(am_libcanclg_la_OBJECTS)
libcanclg_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libcanclg_la_LDFLAGS) $(LDFLAGS) -o $@
libcandbc_la_DEPENDENCIES =
am_libcandbc_la_OBJECTS = src/libcandbc/libcandbc_la-dbcModel.lo \
	src/libcandbc/libcandbc_la-dbcReader.lo \
	src/libcandbc/libcandbc_la-dbcWriter.lo \
	src/libcandbc/libcandbc_la-parser.lo \
	src/libcandbc/libcandbc_la-lexer.lo
libcandbc_la_OBJECTS = $(am_libcandbc_la_OBJECTS)
libcandbc_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libcandbc_la_LDFLAGS) $(LDFLAGS) -o $@
libcanmdf_la_LIBADD =
am_libcanmdf_la_OBJECTS = src/libcanmdf/libcanmdf_la-mdfcg.lo \
	src/libcanmdf/libcanmdf_la-mdfcn.lo \
	src/libcanmdf/libcanmdf_la-mdfdg.lo \
	src/libcanmdf/libcanmdf_la-mdffile.lo \
	src/libcanmdf/libcanmdf_la-mdffilter.lo \
	src/libcanmdf/libcanmdf_la-mdfmodel.lo \
	src/libcanmdf/libcanmdf_la-mdfsg.lo
libcanmdf_la_OBJECTS = $(am_libcanmdf_la_OBJECTS)
libcanmdf_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libcanmdf_la_LDFLAGS) $(LDFLAGS) -o $@
libcanvsb_la_LIBADD =
am_libcanvsb_la_OBJECTS = src/libcanvsb/libcanvsb_la-vsbReader.lo
libcanvsb_la_OBJECTS = $(am_libcanvsb_la_OBJECTS)
libcanvsb_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libcanvsb_la_LDFLAGS) $(LDFLAGS) -o $@
PROGRAMS = $(bin_PROGRAMS)
am_cantomat_OBJECTS = src/cantomat/cantomat-cantomat.$(OBJEXT) \
	src/cantomat/cantomat-messageDecoder.$(OBJEXT) \
	src/cantomat/cantomat-busAssignment.$(OBJEXT) \
	src/cantomat/cantomat-matWrite.$(OBJEXT) \
	src/cantomat/cantomat-messageHash.$(OBJEXT) \
	src/cantomat/cantomat-measurement.$(OBJEXT) \
	src/cantomat/cantomat-signalFormat.$(OBJEXT) \
	src/hashtable/cantomat-hashtable.$(OBJEXT) \
	src/hashtable/cantomat-hashtable_itr.$(OBJEXT)
cantomat_OBJECTS = $(am_cantomat_OBJECTS)
am__DEPENDENCIES_1 =
cantomat_DEPENDENCIES = libcandbc.la libcanasc.la libcanvsb.la \
	libcanclg.la $(am__DEPENDENCIES_1) 
am_dbccopy_OBJECTS = src/dbccopy/dbccopy-dbccopy.$(OBJEXT)
dbccopy_OBJECTS = $(am_dbccopy_OBJECTS)
dbccopy_DEPENDENCIES = libcandbc.la
am_dbcls_OBJECTS = src/dbcls/dbcls-dbcls.$(OBJEXT)
dbcls_OBJECTS = $(am_dbcls_OBJECTS)
dbcls_DEPENDENCIES = libcandbc.la
am_matdump_OBJECTS = src/matdump/matdump-matdump.$(OBJEXT)
matdump_OBJECTS = $(am_matdump_OBJECTS)
matdump_DEPENDENCIES = $(am__DEPENDENCIES_1) 
am_mdftomat_OBJECTS = src/mdftomat/mdftomat-mdftomat.$(OBJEXT)
mdftomat_OBJECTS = $(am_mdftomat_OBJECTS)
mdftomat_DEPENDENCIES = libcanmdf.la $(am__DEPENDENCIES_1) 
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
LEXCOMPILE = $(LEX) $(AM_LFLAGS) $(LFLAGS)
LTLEXCOMPILE = $(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(LEX) $(AM_LFLAGS) $(LFLAGS)
AM_V_LEX = $(am__v_LEX_$(V))
am__v_LEX_ = $(am__v_LEX_$(AM_DEFAULT_VERBOSITY))
am__v_LEX_0 = @echo "  LEX     " $@;
am__v_LEX_1 = 
YLWRAP = $(top_srcdir)/ylwrap
am__yacc_c2h = sed -e s/cc$$/hh/ -e s/cpp$$/hpp/ -e s/cxx$$/hxx/ \
		   -e s/c++$$/h++/ -e s/c$$/h/
YACCCOMPILE = $(YACC) $(AM_YFLAGS) $(YFLAGS)
LTYACCCOMPILE = $(LIBTOOL) $(AM_V_lt) $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(YACC) $(AM_YFLAGS) $(YFLAGS)
AM_V_YACC = $(am__v_YACC_$(V))
am__v_YACC_ = $(am__v_YACC_$(AM_DEFAULT_VERBOSITY))
am__v_YACC_0 = @echo "  YACC    " $@;
am__v_YACC_1 = 
SOURCES = $(libcanasc_la_SOURCES) $(libcanclg_la_SOURCES) \
	$(libcandbc_la_SOURCES) $(libcanmdf_la_SOURCES) \
	$(libcanvsb_la_SOURCES) $(cantomat_SOURCES) $(dbccopy_SOURCES) \
	$(dbcls_SOURCES) $(matdump_SOURCES) $(mdftomat_SOURCES)
DIST_SOURCES = $(libcanasc_la_SOURCES) $(libcanclg_la_SOURCES) \
	$(libcandbc_la_SOURCES) $(libcanmdf_la_SOURCES) \
	$(libcanvsb_la_SOURCES) $(cantomat_SOURCES) $(dbccopy_SOURCES) \
	$(dbcls_SOURCES) $(matdump_SOURCES) $(mdftomat_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
	ctags-recursive dvi-recursive html-recursive info-recursive \
	install-data-recursive install-dvi-recursive \
	install-exec-recursive install-html-recursive \
	install-info-recursive install-pdf-recursive \
	install-ps-recursive install-recursive installcheck-recursive \
	installdirs-recursive pdf-recursive ps-recursive \
	tags-recursive uninstall-recursive
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
HEADERS = $(include_HEADERS)
RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
  distclean-recursive maintainer-clean-recursive
am__recursive_targets = \
  $(RECURSIVE_TARGETS) \
  $(RECURSIVE_CLEAN_TARGETS) \
  $(am__extra_recursive_targets)
AM_RECURSIVE_TARGETS = $(am__recursive_targets:-recursive=) TAGS CTAGS \
	cscope distdir dist dist-all distcheck
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
am__relativize = \
  dir0=`pwd`; \
  sed_first='s,^\([^/]*\)/.*$$,\1,'; \
  sed_rest='s,^[^/]*/*,,'; \
  sed_last='s,^.*/\([^/]*\)$$,\1,'; \
  sed_butlast='s,/*[^/]*$$,,'; \
  while test -n "$$dir1"; do \
    first=`echo "$$dir1" | sed -e "$$sed_first"`; \
    if test "$$first" != "."; then \
      if test "$$first" = ".."; then \
        dir2=`echo "$$dir0" | sed -e "$$sed_last"`/"$$dir2"; \
        dir0=`echo "$$dir0" | sed -e "$$sed_butlast"`; \
      else \
        first2=`echo "$$dir2" | sed -e "$$sed_first"`; \
        if test "$$first2" = "$$first"; then \
          dir2=`echo "$$dir2" | sed -e "$$sed_rest"`; \
        else \
          dir2="../$$dir2"; \
        fi; \
        dir0="$$dir0"/"$$first"; \
      fi; \
    fi; \
    dir1=`echo "$$dir1" | sed -e "$$sed_rest"`; \
  done; \
  reldir="$$dir2"
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /cygdrive/c/Users/aheit/work/Priv/cantools/GitHub/cantools/missing aclocal-1.14
ALLOCA = 
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AS = as
AUTOCONF = ${SHELL} /cygdrive/c/Users/aheit/work/Priv/cantools/GitHub/cantools/missing autoconf
AUTOHEADER = ${SHELL} /cygdrive/c/Users/aheit/work/Priv/cantools/GitHub/cantools/missing autoheader
AUTOMAKE = ${SHELL} /cygdrive/c/Users/aheit/work/Priv/cantools/GitHub/cantools/missing automake-1.14
AWK = gawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CHECK_CFLAGS = 
CHECK_LIBS = -lcheck
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = cygpath -w
DEFS = $(YYDEBUG) -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = dlltool
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = .exe
FGREP = /usr/bin/grep -F
GLIB_CFLAGS = -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
GLIB_LIBS = -lglib-2.0 -lintl
GREP = /usr/bin/grep
HDF5_LIB = -lhdf5
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/x86_64-pc-cygwin/bin/ld.exe
LDFLAGS = 
LEX = flex
LEXLIB = -lfl
LEX_OUTPUT_ROOT = lex.yy
LIBOBJS = 
LIBS = -lz 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIBTOOL_DEPS = ./ltmain.sh
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
LT_SYS_LIBRARY_PATH = 
MAKEINFO = ${SHELL} /cygdrive/c/Users/aheit/work/Priv/cantools/GitHub/cantools/missing makeinfo
MANIFEST_TOOL = :
MATIO_CFLAGS = -I//include
MATIO_LIBS = -lmatio
MKDIR_P = /usr/bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = cantools
PACKAGE_BUGREPORT = andreas.heitmann@gmail.com
PACKAGE_NAME = cantools
PACKAGE_STRING = cantools 0.19
PACKAGE_TARNAME = cantools
PACKAGE_URL = 
PACKAGE_VERSION = 0.19
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
POW_LIB = 
RANLIB = ranlib
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 0.19
YACC = bison -y
YFLAGS = 
ZLIB_CFLAGS = 
ZLIB_LIBS = -lz
Z_LIB = -lz
abs_builddir = /cygdrive/c/Users/aheit/work/Priv/cantools/GitHub/cantools
abs_srcdir = /cygdrive/c/Users/aheit/work/Priv/cantools/GitHub/cantools
abs_top_builddir = /cygdrive/c/Users/aheit/work/Priv/cantools/GitHub/cantools
abs_top_srcdir = /cygdrive/c/Users/aheit/work/Priv/cantools/GitHub/cantools
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-cygwin
build_alias = 
build_cpu = x86_64
build_os = cygwin
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-cygwin
host_alias = 
host_cpu = x86_64
host_os = cygwin
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /cygdrive/c/Users/aheit/work/Priv/cantools/GitHub/cantools/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
version_info = 0:19:0
SUBDIRS = . tests
AUTOMAKE_OPTIONS = foreign subdir-objects
ACLOCAL_AMFLAGS = -I m4

#	
# What to build and install
#
lib_LTLIBRARIES = libcandbc.la libcanasc.la libcanmdf.la libcanvsb.la \
	          libcanclg.la


#
# dbcls
#
dbcls_SOURCES = src/dbcls/dbcls.c
dbcls_CPPFLAGS = -I$(top_srcdir)/src/libcandbc
dbcls_LDADD = libcandbc.la -lm

#
# dbccopy
#
dbccopy_SOURCES = src/dbccopy/dbccopy.c
dbccopy_CPPFLAGS = -I$(top_srcdir)/src/libcandbc
dbccopy_LDADD = libcandbc.la -lm

#
# cantomat
#
cantomat_SOURCES = src/cantomat/cantomat.c \
		   src/cantomat/messageDecoder.c \
		   src/cantomat/busAssignment.c \
		   src/cantomat/matWrite.c \
		   src/cantomat/messageHash.c \
		   src/cantomat/measurement.c \
		   src/cantomat/signalFormat.c \
		   src/cantomat/measurement.h \
		   src/cantomat/signalFormat.h \
		   src/cantomat/busAssignment.h \
		   src/cantomat/matWrite.h \
		   src/cantomat/messageHash.h \
		   src/hashtable/hashtable.c \
		   src/hashtable/hashtable_itr.c \
		   src/hashtable/hashtable.h \
		   src/hashtable/hashtable_itr.h \
		   src/hashtable/hashtable_private.h

cantomat_CPPFLAGS = -I//include \
	   -I$(top_srcdir)/src/libcanasc \
           -I$(top_srcdir)/src/libcanclg \
	   -I$(top_srcdir)/src/libcandbc \
	   -I$(top_srcdir)/src/libcanvsb \
           -I$(top_srcdir)/src/cantomat \
	   -I$(top_srcdir)/src/hashtable

cantomat_LDADD = libcandbc.la libcanasc.la libcanvsb.la libcanclg.la \
	-lmatio -lz $(HDF5_LIB)  -lm

#
# mdftomat
#
mdftomat_SOURCES = src/mdftomat/mdftomat.c \
                   src/mdftomat/mdftomat.h

mdftomat_CPPFLAGS = -I//include \
	   -I$(top_srcdir)/src/libcanmdf

mdftomat_LDADD = libcanmdf.la -lmatio -lz $(HDF5_LIB) 

#
# matdump
#
matdump_SOURCES = src/matdump/matdump.c \
                  src/matdump/matdump.h

matdump_CPPFLAGS = -I//include
matdump_LDADD = -lmatio -lz $(HDF5_LIB) 

# additional include pathes necessary
AM_CPPFLAGS = 

# YACC: generate token defines for LEX
AM_YFLAGS = -d
YYDEBUG = -DYYDEBUG=1

#
# library headers, source, etc.
#
include_HEADERS = src/libcandbc/dbcModel.h \
		 src/libcandbc/dbcTypes.h \
		 src/libcandbc/dbcReader.h \
		 src/libcandbc/dbcWriter.h \
		 src/libcanmdf/mdfcg.h \
		 src/libcanmdf/mdfdg.h \
		 src/libcanmdf/mdffile.h \
		 src/libcanmdf/mdffilter.h \
		 src/libcanasc/ascReader.h \
		 src/libcanvsb/vsbReader.h \
		 src/libcanclg/clgReader.h \
		 src/cantomat/messageDecoder.h \
		 src/libcanmdf/mdfcn.h \
		 src/libcanmdf/mdfswap.h \
		 src/libcanmdf/mdftypes.h

libcandbc_la_SOURCES = \
	src/libcandbc/dbcModel.c \
	src/libcandbc/dbcReader.c \
	src/libcandbc/dbcWriter.c \
	src/libcandbc/parser.y \
	src/libcandbc/lexer.l

libcandbc_la_LIBADD = -lm
libcanasc_la_SOURCES = src/libcanasc/ascReader.c
libcanvsb_la_SOURCES = src/libcanvsb/vsbReader.c
libcanclg_la_SOURCES = src/libcanclg/clgReader.c
libcanmdf_la_SOURCES = \
	src/libcanmdf/mdfcg.c \
	src/libcanmdf/mdfcn.c \
	src/libcanmdf/mdfdg.c \
	src/libcanmdf/mdffile.c \
	src/libcanmdf/mdffilter.c \
	src/libcanmdf/mdfmodel.c \
	src/libcanmdf/mdfsg.c

libcanmdf_CPPFLAGS = -I//include
libcandbc_la_CPPFLAGS = -I$(top_builddir)/src/libcandbc \
                       -I$(top_srcdir)/src/libcandbc

libcandbc_la_LDFLAGS = -no-undefined -version-info 0:19:0
libcanasc_la_CPPFLAGS = -I$(top_builddir)/src/libcanasc \
		       -I$(top_srcdir)/src/libcandbc \
		       -I$(top_srcdir)/src/cantomat \
                       -I$(top_srcdir)/src/hashtable

libcanasc_la_LDFLAGS = -no-undefined -version-info 0:19:0
libcanvsb_la_CPPFLAGS = -I$(top_builddir)/src/libcanvsb \
		       -I$(top_srcdir)/src/libcandbc \
                       -I$(top_srcdir)/src/hashtable

libcanvsb_la_LDFLAGS = -no-undefined -version-info 0:19:0
libcanclg_la_CPPFLAGS = -I$(top_builddir)/src/libcanclg \
		       -I$(top_srcdir)/src/libcandbc \
                       -I$(top_srcdir)/src/hashtable

libcanclg_la_LDFLAGS = -no-undefined -version-info 0:19:0
libcanmdf_la_CPPFLAGS = -I$(top_builddir)/src/libcanmdf -I//include
libcanmdf_la_LDFLAGS = -no-undefined -version-info 0:19:0
MAINTAINERCLEANFILES = \
	src/libcandbc/parser.c \
	src/libcandbc/parser.h \
	src/libcandbc/lexer.c

all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .c .l .lo .o .obj .y
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}
src/libcanasc/$(am__dirstamp):
	@$(MKDIR_P) src/libcanasc
	@: > src/libcanasc/$(am__dirstamp)
src/libcanasc/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/libcanasc/$(DEPDIR)
	@: > src/libcanasc/$(DEPDIR)/$(am__dirstamp)
src/libcanasc/libcanasc_la-ascReader.lo:  \
	src/libcanasc/$(am__dirstamp) \
	src/libcanasc/$(DEPDIR)/$(am__dirstamp)

libcanasc.la: $(libcanasc_la_OBJECTS) $(libcanasc_la_DEPENDENCIES) $(EXTRA_libcanasc_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libcanasc_la_LINK) -rpath $(libdir) $(libcanasc_la_OBJECTS) $(libcanasc_la_LIBADD) $(LIBS)
src/libcanclg/$(am__dirstamp):
	@$(MKDIR_P) src/libcanclg
	@: > src/libcanclg/$(am__dirstamp)
src/libcanclg/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/libcanclg/$(DEPDIR)
	@: > src/libcanclg/$(DEPDIR)/$(am__dirstamp)
src/libcanclg/libcanclg_la-clgReader.lo:  \
	src/libcanclg/$(am__dirstamp) \
	src/libcanclg/$(DEPDIR)/$(am__dirstamp)

libcanclg.la: $(libcanclg_la_OBJECTS) $(libcanclg_la_DEPENDENCIES) $(EXTRA_libcanclg_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libcanclg_la_LINK) -rpath $(libdir) $(libcanclg_la_OBJECTS) $(libcanclg_la_LIBADD) $(LIBS)
src/libcandbc/$(am__dirstamp):
	@$(MKDIR_P) src/libcandbc
	@: > src/libcandbc/$(am__dirstamp)
src/libcandbc/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/libcandbc/$(DEPDIR)
	@: > src/libcandbc/$(DEPDIR)/$(am__dirstamp)
src/libcandbc/libcandbc_la-dbcModel.lo: src/libcandbc/$(am__dirstamp) \
	src/libcandbc/$(DEPDIR)/$(am__dirstamp)
src/libcandbc/libcandbc_la-dbcReader.lo:  \
	src/libcandbc/$(am__dirstamp) \
	src/libcandbc/$(DEPDIR)/$(am__dirstamp)
src/libcandbc/libcandbc_la-dbcWriter.lo:  \
	src/libcandbc/$(am__dirstamp) \
	src/libcandbc/$(DEPDIR)/$(am__dirstamp)
src/libcandbc/parser.h: src/libcandbc/parser.c
	@if test ! -f $@; then rm -f src/libcandbc/parser.c; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) src/libcandbc/parser.c; else :; fi
src/libcandbc/libcandbc_la-parser.lo: src/libcandbc/$(am__dirstamp) \
	src/libcandbc/$(DEPDIR)/$(am__dirstamp)
src/libcandbc/libcandbc_la-lexer.lo: src/libcandbc/$(am__dirstamp) \
	src/libcandbc/$(DEPDIR)/$(am__dirstamp)

libcandbc.la: $(libcandbc_la_OBJECTS) $(libcandbc_la_DEPENDENCIES) $(EXTRA_libcandbc_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libcandbc_la_LINK) -rpath $(libdir) $(libcandbc_la_OBJECTS) $(libcandbc_la_LIBADD) $(LIBS)
src/libcanmdf/$(am__dirstamp):
	@$(MKDIR_P) src/libcanmdf
	@: > src/libcanmdf/$(am__dirstamp)
src/libcanmdf/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/libcanmdf/$(DEPDIR)
	@: > src/libcanmdf/$(DEPDIR)/$(am__dirstamp)
src/libcanmdf/libcanmdf_la-mdfcg.lo: src/libcanmdf/$(am__dirstamp) \
	src/libcanmdf/$(DEPDIR)/$(am__dirstamp)
src/libcanmdf/libcanmdf_la-mdfcn.lo: src/libcanmdf/$(am__dirstamp) \
	src/libcanmdf/$(DEPDIR)/$(am__dirstamp)
src/libcanmdf/libcanmdf_la-mdfdg.lo: src/libcanmdf/$(am__dirstamp) \
	src/libcanmdf/$(DEPDIR)/$(am__dirstamp)
src/libcanmdf/libcanmdf_la-mdffile.lo: src/libcanmdf/$(am__dirstamp) \
	src/libcanmdf/$(DEPDIR)/$(am__dirstamp)
src/libcanmdf/libcanmdf_la-mdffilter.lo:  \
	src/libcanmdf/$(am__dirstamp) \
	src/libcanmdf/$(DEPDIR)/$(am__dirstamp)
src/libcanmdf/libcanmdf_la-mdfmodel.lo: src/libcanmdf/$(am__dirstamp) \
	src/libcanmdf/$(DEPDIR)/$(am__dirstamp)
src/libcanmdf/libcanmdf_la-mdfsg.lo: src/libcanmdf/$(am__dirstamp) \
	src/libcanmdf/$(DEPDIR)/$(am__dirstamp)

libcanmdf.la: $(libcanmdf_la_OBJECTS) $(libcanmdf_la_DEPENDENCIES) $(EXTRA_libcanmdf_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libcanmdf_la_LINK) -rpath $(libdir) $(libcanmdf_la_OBJECTS) $(libcanmdf_la_LIBADD) $(LIBS)
src/libcanvsb/$(am__dirstamp):
	@$(MKDIR_P) src/libcanvsb
	@: > src/libcanvsb/$(am__dirstamp)
src/libcanvsb/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/libcanvsb/$(DEPDIR)
	@: > src/libcanvsb/$(DEPDIR)/$(am__dirstamp)
src/libcanvsb/libcanvsb_la-vsbReader.lo:  \
	src/libcanvsb/$(am__dirstamp) \
	src/libcanvsb/$(DEPDIR)/$(am__dirstamp)

libcanvsb.la: $(libcanvsb_la_OBJECTS) $(libcanvsb_la_DEPENDENCIES) $(EXTRA_libcanvsb_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libcanvsb_la_LINK) -rpath $(libdir) $(libcanvsb_la_OBJECTS) $(libcanvsb_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
src/cantomat/$(am__dirstamp):
	@$(MKDIR_P) src/cantomat
	@: > src/cantomat/$(am__dirstamp)
src/cantomat/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/cantomat/$(DEPDIR)
	@: > src/cantomat/$(DEPDIR)/$(am__dirstamp)
src/cantomat/cantomat-cantomat.$(OBJEXT):  \
	src/cantomat/$(am__dirstamp) \
	src/cantomat/$(DEPDIR)/$(am__dirstamp)
src/cantomat/cantomat-messageDecoder.$(OBJEXT):  \
	src/cantomat/$(am__dirstamp) \
	src/cantomat/$(DEPDIR)/$(am__dirstamp)
src/cantomat/cantomat-busAssignment.$(OBJEXT):  \
	src/cantomat/$(am__dirstamp) \
	src/cantomat/$(DEPDIR)/$(am__dirstamp)
src/cantomat/cantomat-matWrite.$(OBJEXT):  \
	src/cantomat/$(am__dirstamp) \
	src/cantomat/$(DEPDIR)/$(am__dirstamp)
src/cantomat/cantomat-messageHash.$(OBJEXT):  \
	src/cantomat/$(am__dirstamp) \
	src/cantomat/$(DEPDIR)/$(am__dirstamp)
src/cantomat/cantomat-measurement.$(OBJEXT):  \
	src/cantomat/$(am__dirstamp) \
	src/cantomat/$(DEPDIR)/$(am__dirstamp)
src/cantomat/cantomat-signalFormat.$(OBJEXT):  \
	src/cantomat/$(am__dirstamp) \
	src/cantomat/$(DEPDIR)/$(am__dirstamp)
src/hashtable/$(am__dirstamp):
	@$(MKDIR_P) src/hashtable
	@: > src/hashtable/$(am__dirstamp)
src/hashtable/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/hashtable/$(DEPDIR)
	@: > src/hashtable/$(DEPDIR)/$(am__dirstamp)
src/hashtable/cantomat-hashtable.$(OBJEXT):  \
	src/hashtable/$(am__dirstamp) \
	src/hashtable/$(DEPDIR)/$(am__dirstamp)
src/hashtable/cantomat-hashtable_itr.$(OBJEXT):  \
	src/hashtable/$(am__dirstamp) \
	src/hashtable/$(DEPDIR)/$(am__dirstamp)

cantomat$(EXEEXT): $(cantomat_OBJECTS) $(cantomat_DEPENDENCIES) $(EXTRA_cantomat_DEPENDENCIES) 
	@rm -f cantomat$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(cantomat_OBJECTS) $(cantomat_LDADD) $(LIBS)
src/dbccopy/$(am__dirstamp):
	@$(MKDIR_P) src/dbccopy
	@: > src/dbccopy/$(am__dirstamp)
src/dbccopy/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/dbccopy/$(DEPDIR)
	@: > src/dbccopy/$(DEPDIR)/$(am__dirstamp)
src/dbccopy/dbccopy-dbccopy.$(OBJEXT): src/dbccopy/$(am__dirstamp) \
	src/dbccopy/$(DEPDIR)/$(am__dirstamp)

dbccopy$(EXEEXT): $(dbccopy_OBJECTS) $(dbccopy_DEPENDENCIES) $(EXTRA_dbccopy_DEPENDENCIES) 
	@rm -f dbccopy$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(dbccopy_OBJECTS) $(dbccopy_LDADD) $(LIBS)
src/dbcls/$(am__dirstamp):
	@$(MKDIR_P) src/dbcls
	@: > src/dbcls/$(am__dirstamp)
src/dbcls/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/dbcls/$(DEPDIR)
	@: > src/dbcls/$(DEPDIR)/$(am__dirstamp)
src/dbcls/dbcls-dbcls.$(OBJEXT): src/dbcls/$(am__dirstamp) \
	src/dbcls/$(DEPDIR)/$(am__dirstamp)

dbcls$(EXEEXT): $(dbcls_OBJECTS) $(dbcls_DEPENDENCIES) $(EXTRA_dbcls_DEPENDENCIES) 
	@rm -f dbcls$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(dbcls_OBJECTS) $(dbcls_LDADD) $(LIBS)
src/matdump/$(am__dirstamp):
	@$(MKDIR_P) src/matdump
	@: > src/matdump/$(am__dirstamp)
src/matdump/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/matdump/$(DEPDIR)
	@: > src/matdump/$(DEPDIR)/$(am__dirstamp)
src/matdump/matdump-matdump.$(OBJEXT): src/matdump/$(am__dirstamp) \
	src/matdump/$(DEPDIR)/$(am__dirstamp)

matdump$(EXEEXT): $(matdump_OBJECTS) $(matdump_DEPENDENCIES) $(EXTRA_matdump_DEPENDENCIES) 
	@rm -f matdump$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(matdump_OBJECTS) $(matdump_LDADD) $(LIBS)
src/mdftomat/$(am__dirstamp):
	@$(MKDIR_P) src/mdftomat
	@: > src/mdftomat/$(am__dirstamp)
src/mdftomat/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) src/mdftomat/$(DEPDIR)
	@: > src/mdftomat/$(DEPDIR)/$(am__dirstamp)
src/mdftomat/mdftomat-mdftomat.$(OBJEXT):  \
	src/mdftomat/$(am__dirstamp) \
	src/mdftomat/$(DEPDIR)/$(am__dirstamp)

mdftomat$(EXEEXT): $(mdftomat_OBJECTS) $(mdftomat_DEPENDENCIES) $(EXTRA_mdftomat_DEPENDENCIES) 
	@rm -f mdftomat$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(mdftomat_OBJECTS) $(mdftomat_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f src/cantomat/*.$(OBJEXT)
	-rm -f src/dbccopy/*.$(OBJEXT)
	-rm -f src/dbcls/*.$(OBJEXT)
	-rm -f src/hashtable/*.$(OBJEXT)
	-rm -f src/libcanasc/*.$(OBJEXT)
	-rm -f src/libcanasc/*.lo
	-rm -f src/libcanclg/*.$(OBJEXT)
	-rm -f src/libcanclg/*.lo
	-rm -f src/libcandbc/*.$(OBJEXT)
	-rm -f src/libcandbc/*.lo
	-rm -f src/libcanmdf/*.$(OBJEXT)
	-rm -f src/libcanmdf/*.lo
	-rm -f src/libcanvsb/*.$(OBJEXT)
	-rm -f src/libcanvsb/*.lo
	-rm -f src/matdump/*.$(OBJEXT)
	-rm -f src/mdftomat/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/malloc.Po
include $(DEPDIR)/realloc.Po
include $(DEPDIR)/strndup.Po
include $(DEPDIR)/strnlen.Po
include $(DEPDIR)/strtod.Po
include $(DEPDIR)/strtok_r.Po
include src/cantomat/$(DEPDIR)/cantomat-busAssignment.Po
include src/cantomat/$(DEPDIR)/cantomat-cantomat.Po
include src/cantomat/$(DEPDIR)/cantomat-matWrite.Po
include src/cantomat/$(DEPDIR)/cantomat-measurement.Po
include src/cantomat/$(DEPDIR)/cantomat-messageDecoder.Po
include src/cantomat/$(DEPDIR)/cantomat-messageHash.Po
include src/cantomat/$(DEPDIR)/cantomat-signalFormat.Po
include src/dbccopy/$(DEPDIR)/dbccopy-dbccopy.Po
include src/dbcls/$(DEPDIR)/dbcls-dbcls.Po
include src/hashtable/$(DEPDIR)/cantomat-hashtable.Po
include src/hashtable/$(DEPDIR)/cantomat-hashtable_itr.Po
include src/libcanasc/$(DEPDIR)/libcanasc_la-ascReader.Plo
include src/libcanclg/$(DEPDIR)/libcanclg_la-clgReader.Plo
include src/libcandbc/$(DEPDIR)/libcandbc_la-dbcModel.Plo
include src/libcandbc/$(DEPDIR)/libcandbc_la-dbcReader.Plo
include src/libcandbc/$(DEPDIR)/libcandbc_la-dbcWriter.Plo
include src/libcandbc/$(DEPDIR)/libcandbc_la-lexer.Plo
include src/libcandbc/$(DEPDIR)/libcandbc_la-parser.Plo
include src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfcg.Plo
include src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfcn.Plo
include src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfdg.Plo
include src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdffile.Plo
include src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdffilter.Plo
include src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfmodel.Plo
include src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfsg.Plo
include src/libcanvsb/$(DEPDIR)/libcanvsb_la-vsbReader.Plo
include src/matdump/$(DEPDIR)/matdump-matdump.Po
include src/mdftomat/$(DEPDIR)/mdftomat-mdftomat.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

src/libcanasc/libcanasc_la-ascReader.lo: src/libcanasc/ascReader.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanasc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcanasc/libcanasc_la-ascReader.lo -MD -MP -MF src/libcanasc/$(DEPDIR)/libcanasc_la-ascReader.Tpo -c -o src/libcanasc/libcanasc_la-ascReader.lo `test -f 'src/libcanasc/ascReader.c' || echo '$(srcdir)/'`src/libcanasc/ascReader.c
	$(AM_V_at)$(am__mv) src/libcanasc/$(DEPDIR)/libcanasc_la-ascReader.Tpo src/libcanasc/$(DEPDIR)/libcanasc_la-ascReader.Plo
#	$(AM_V_CC)source='src/libcanasc/ascReader.c' object='src/libcanasc/libcanasc_la-ascReader.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanasc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcanasc/libcanasc_la-ascReader.lo `test -f 'src/libcanasc/ascReader.c' || echo '$(srcdir)/'`src/libcanasc/ascReader.c

src/libcanclg/libcanclg_la-clgReader.lo: src/libcanclg/clgReader.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanclg_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcanclg/libcanclg_la-clgReader.lo -MD -MP -MF src/libcanclg/$(DEPDIR)/libcanclg_la-clgReader.Tpo -c -o src/libcanclg/libcanclg_la-clgReader.lo `test -f 'src/libcanclg/clgReader.c' || echo '$(srcdir)/'`src/libcanclg/clgReader.c
	$(AM_V_at)$(am__mv) src/libcanclg/$(DEPDIR)/libcanclg_la-clgReader.Tpo src/libcanclg/$(DEPDIR)/libcanclg_la-clgReader.Plo
#	$(AM_V_CC)source='src/libcanclg/clgReader.c' object='src/libcanclg/libcanclg_la-clgReader.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanclg_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcanclg/libcanclg_la-clgReader.lo `test -f 'src/libcanclg/clgReader.c' || echo '$(srcdir)/'`src/libcanclg/clgReader.c

src/libcandbc/libcandbc_la-dbcModel.lo: src/libcandbc/dbcModel.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcandbc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcandbc/libcandbc_la-dbcModel.lo -MD -MP -MF src/libcandbc/$(DEPDIR)/libcandbc_la-dbcModel.Tpo -c -o src/libcandbc/libcandbc_la-dbcModel.lo `test -f 'src/libcandbc/dbcModel.c' || echo '$(srcdir)/'`src/libcandbc/dbcModel.c
	$(AM_V_at)$(am__mv) src/libcandbc/$(DEPDIR)/libcandbc_la-dbcModel.Tpo src/libcandbc/$(DEPDIR)/libcandbc_la-dbcModel.Plo
#	$(AM_V_CC)source='src/libcandbc/dbcModel.c' object='src/libcandbc/libcandbc_la-dbcModel.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcandbc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcandbc/libcandbc_la-dbcModel.lo `test -f 'src/libcandbc/dbcModel.c' || echo '$(srcdir)/'`src/libcandbc/dbcModel.c

src/libcandbc/libcandbc_la-dbcReader.lo: src/libcandbc/dbcReader.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcandbc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcandbc/libcandbc_la-dbcReader.lo -MD -MP -MF src/libcandbc/$(DEPDIR)/libcandbc_la-dbcReader.Tpo -c -o src/libcandbc/libcandbc_la-dbcReader.lo `test -f 'src/libcandbc/dbcReader.c' || echo '$(srcdir)/'`src/libcandbc/dbcReader.c
	$(AM_V_at)$(am__mv) src/libcandbc/$(DEPDIR)/libcandbc_la-dbcReader.Tpo src/libcandbc/$(DEPDIR)/libcandbc_la-dbcReader.Plo
#	$(AM_V_CC)source='src/libcandbc/dbcReader.c' object='src/libcandbc/libcandbc_la-dbcReader.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcandbc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcandbc/libcandbc_la-dbcReader.lo `test -f 'src/libcandbc/dbcReader.c' || echo '$(srcdir)/'`src/libcandbc/dbcReader.c

src/libcandbc/libcandbc_la-dbcWriter.lo: src/libcandbc/dbcWriter.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcandbc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcandbc/libcandbc_la-dbcWriter.lo -MD -MP -MF src/libcandbc/$(DEPDIR)/libcandbc_la-dbcWriter.Tpo -c -o src/libcandbc/libcandbc_la-dbcWriter.lo `test -f 'src/libcandbc/dbcWriter.c' || echo '$(srcdir)/'`src/libcandbc/dbcWriter.c
	$(AM_V_at)$(am__mv) src/libcandbc/$(DEPDIR)/libcandbc_la-dbcWriter.Tpo src/libcandbc/$(DEPDIR)/libcandbc_la-dbcWriter.Plo
#	$(AM_V_CC)source='src/libcandbc/dbcWriter.c' object='src/libcandbc/libcandbc_la-dbcWriter.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcandbc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcandbc/libcandbc_la-dbcWriter.lo `test -f 'src/libcandbc/dbcWriter.c' || echo '$(srcdir)/'`src/libcandbc/dbcWriter.c

src/libcandbc/libcandbc_la-parser.lo: src/libcandbc/parser.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcandbc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcandbc/libcandbc_la-parser.lo -MD -MP -MF src/libcandbc/$(DEPDIR)/libcandbc_la-parser.Tpo -c -o src/libcandbc/libcandbc_la-parser.lo `test -f 'src/libcandbc/parser.c' || echo '$(srcdir)/'`src/libcandbc/parser.c
	$(AM_V_at)$(am__mv) src/libcandbc/$(DEPDIR)/libcandbc_la-parser.Tpo src/libcandbc/$(DEPDIR)/libcandbc_la-parser.Plo
#	$(AM_V_CC)source='src/libcandbc/parser.c' object='src/libcandbc/libcandbc_la-parser.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcandbc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcandbc/libcandbc_la-parser.lo `test -f 'src/libcandbc/parser.c' || echo '$(srcdir)/'`src/libcandbc/parser.c

src/libcandbc/libcandbc_la-lexer.lo: src/libcandbc/lexer.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcandbc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcandbc/libcandbc_la-lexer.lo -MD -MP -MF src/libcandbc/$(DEPDIR)/libcandbc_la-lexer.Tpo -c -o src/libcandbc/libcandbc_la-lexer.lo `test -f 'src/libcandbc/lexer.c' || echo '$(srcdir)/'`src/libcandbc/lexer.c
	$(AM_V_at)$(am__mv) src/libcandbc/$(DEPDIR)/libcandbc_la-lexer.Tpo src/libcandbc/$(DEPDIR)/libcandbc_la-lexer.Plo
#	$(AM_V_CC)source='src/libcandbc/lexer.c' object='src/libcandbc/libcandbc_la-lexer.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcandbc_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcandbc/libcandbc_la-lexer.lo `test -f 'src/libcandbc/lexer.c' || echo '$(srcdir)/'`src/libcandbc/lexer.c

src/libcanmdf/libcanmdf_la-mdfcg.lo: src/libcanmdf/mdfcg.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcanmdf/libcanmdf_la-mdfcg.lo -MD -MP -MF src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfcg.Tpo -c -o src/libcanmdf/libcanmdf_la-mdfcg.lo `test -f 'src/libcanmdf/mdfcg.c' || echo '$(srcdir)/'`src/libcanmdf/mdfcg.c
	$(AM_V_at)$(am__mv) src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfcg.Tpo src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfcg.Plo
#	$(AM_V_CC)source='src/libcanmdf/mdfcg.c' object='src/libcanmdf/libcanmdf_la-mdfcg.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcanmdf/libcanmdf_la-mdfcg.lo `test -f 'src/libcanmdf/mdfcg.c' || echo '$(srcdir)/'`src/libcanmdf/mdfcg.c

src/libcanmdf/libcanmdf_la-mdfcn.lo: src/libcanmdf/mdfcn.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcanmdf/libcanmdf_la-mdfcn.lo -MD -MP -MF src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfcn.Tpo -c -o src/libcanmdf/libcanmdf_la-mdfcn.lo `test -f 'src/libcanmdf/mdfcn.c' || echo '$(srcdir)/'`src/libcanmdf/mdfcn.c
	$(AM_V_at)$(am__mv) src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfcn.Tpo src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfcn.Plo
#	$(AM_V_CC)source='src/libcanmdf/mdfcn.c' object='src/libcanmdf/libcanmdf_la-mdfcn.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcanmdf/libcanmdf_la-mdfcn.lo `test -f 'src/libcanmdf/mdfcn.c' || echo '$(srcdir)/'`src/libcanmdf/mdfcn.c

src/libcanmdf/libcanmdf_la-mdfdg.lo: src/libcanmdf/mdfdg.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcanmdf/libcanmdf_la-mdfdg.lo -MD -MP -MF src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfdg.Tpo -c -o src/libcanmdf/libcanmdf_la-mdfdg.lo `test -f 'src/libcanmdf/mdfdg.c' || echo '$(srcdir)/'`src/libcanmdf/mdfdg.c
	$(AM_V_at)$(am__mv) src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfdg.Tpo src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfdg.Plo
#	$(AM_V_CC)source='src/libcanmdf/mdfdg.c' object='src/libcanmdf/libcanmdf_la-mdfdg.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcanmdf/libcanmdf_la-mdfdg.lo `test -f 'src/libcanmdf/mdfdg.c' || echo '$(srcdir)/'`src/libcanmdf/mdfdg.c

src/libcanmdf/libcanmdf_la-mdffile.lo: src/libcanmdf/mdffile.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcanmdf/libcanmdf_la-mdffile.lo -MD -MP -MF src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdffile.Tpo -c -o src/libcanmdf/libcanmdf_la-mdffile.lo `test -f 'src/libcanmdf/mdffile.c' || echo '$(srcdir)/'`src/libcanmdf/mdffile.c
	$(AM_V_at)$(am__mv) src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdffile.Tpo src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdffile.Plo
#	$(AM_V_CC)source='src/libcanmdf/mdffile.c' object='src/libcanmdf/libcanmdf_la-mdffile.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcanmdf/libcanmdf_la-mdffile.lo `test -f 'src/libcanmdf/mdffile.c' || echo '$(srcdir)/'`src/libcanmdf/mdffile.c

src/libcanmdf/libcanmdf_la-mdffilter.lo: src/libcanmdf/mdffilter.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcanmdf/libcanmdf_la-mdffilter.lo -MD -MP -MF src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdffilter.Tpo -c -o src/libcanmdf/libcanmdf_la-mdffilter.lo `test -f 'src/libcanmdf/mdffilter.c' || echo '$(srcdir)/'`src/libcanmdf/mdffilter.c
	$(AM_V_at)$(am__mv) src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdffilter.Tpo src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdffilter.Plo
#	$(AM_V_CC)source='src/libcanmdf/mdffilter.c' object='src/libcanmdf/libcanmdf_la-mdffilter.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcanmdf/libcanmdf_la-mdffilter.lo `test -f 'src/libcanmdf/mdffilter.c' || echo '$(srcdir)/'`src/libcanmdf/mdffilter.c

src/libcanmdf/libcanmdf_la-mdfmodel.lo: src/libcanmdf/mdfmodel.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcanmdf/libcanmdf_la-mdfmodel.lo -MD -MP -MF src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfmodel.Tpo -c -o src/libcanmdf/libcanmdf_la-mdfmodel.lo `test -f 'src/libcanmdf/mdfmodel.c' || echo '$(srcdir)/'`src/libcanmdf/mdfmodel.c
	$(AM_V_at)$(am__mv) src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfmodel.Tpo src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfmodel.Plo
#	$(AM_V_CC)source='src/libcanmdf/mdfmodel.c' object='src/libcanmdf/libcanmdf_la-mdfmodel.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcanmdf/libcanmdf_la-mdfmodel.lo `test -f 'src/libcanmdf/mdfmodel.c' || echo '$(srcdir)/'`src/libcanmdf/mdfmodel.c

src/libcanmdf/libcanmdf_la-mdfsg.lo: src/libcanmdf/mdfsg.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcanmdf/libcanmdf_la-mdfsg.lo -MD -MP -MF src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfsg.Tpo -c -o src/libcanmdf/libcanmdf_la-mdfsg.lo `test -f 'src/libcanmdf/mdfsg.c' || echo '$(srcdir)/'`src/libcanmdf/mdfsg.c
	$(AM_V_at)$(am__mv) src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfsg.Tpo src/libcanmdf/$(DEPDIR)/libcanmdf_la-mdfsg.Plo
#	$(AM_V_CC)source='src/libcanmdf/mdfsg.c' object='src/libcanmdf/libcanmdf_la-mdfsg.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanmdf_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcanmdf/libcanmdf_la-mdfsg.lo `test -f 'src/libcanmdf/mdfsg.c' || echo '$(srcdir)/'`src/libcanmdf/mdfsg.c

src/libcanvsb/libcanvsb_la-vsbReader.lo: src/libcanvsb/vsbReader.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanvsb_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/libcanvsb/libcanvsb_la-vsbReader.lo -MD -MP -MF src/libcanvsb/$(DEPDIR)/libcanvsb_la-vsbReader.Tpo -c -o src/libcanvsb/libcanvsb_la-vsbReader.lo `test -f 'src/libcanvsb/vsbReader.c' || echo '$(srcdir)/'`src/libcanvsb/vsbReader.c
	$(AM_V_at)$(am__mv) src/libcanvsb/$(DEPDIR)/libcanvsb_la-vsbReader.Tpo src/libcanvsb/$(DEPDIR)/libcanvsb_la-vsbReader.Plo
#	$(AM_V_CC)source='src/libcanvsb/vsbReader.c' object='src/libcanvsb/libcanvsb_la-vsbReader.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libcanvsb_la_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/libcanvsb/libcanvsb_la-vsbReader.lo `test -f 'src/libcanvsb/vsbReader.c' || echo '$(srcdir)/'`src/libcanvsb/vsbReader.c

src/cantomat/cantomat-cantomat.o: src/cantomat/cantomat.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-cantomat.o -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-cantomat.Tpo -c -o src/cantomat/cantomat-cantomat.o `test -f 'src/cantomat/cantomat.c' || echo '$(srcdir)/'`src/cantomat/cantomat.c
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-cantomat.Tpo src/cantomat/$(DEPDIR)/cantomat-cantomat.Po
#	$(AM_V_CC)source='src/cantomat/cantomat.c' object='src/cantomat/cantomat-cantomat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-cantomat.o `test -f 'src/cantomat/cantomat.c' || echo '$(srcdir)/'`src/cantomat/cantomat.c

src/cantomat/cantomat-cantomat.obj: src/cantomat/cantomat.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-cantomat.obj -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-cantomat.Tpo -c -o src/cantomat/cantomat-cantomat.obj `if test -f 'src/cantomat/cantomat.c'; then $(CYGPATH_W) 'src/cantomat/cantomat.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/cantomat.c'; fi`
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-cantomat.Tpo src/cantomat/$(DEPDIR)/cantomat-cantomat.Po
#	$(AM_V_CC)source='src/cantomat/cantomat.c' object='src/cantomat/cantomat-cantomat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-cantomat.obj `if test -f 'src/cantomat/cantomat.c'; then $(CYGPATH_W) 'src/cantomat/cantomat.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/cantomat.c'; fi`

src/cantomat/cantomat-messageDecoder.o: src/cantomat/messageDecoder.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-messageDecoder.o -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-messageDecoder.Tpo -c -o src/cantomat/cantomat-messageDecoder.o `test -f 'src/cantomat/messageDecoder.c' || echo '$(srcdir)/'`src/cantomat/messageDecoder.c
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-messageDecoder.Tpo src/cantomat/$(DEPDIR)/cantomat-messageDecoder.Po
#	$(AM_V_CC)source='src/cantomat/messageDecoder.c' object='src/cantomat/cantomat-messageDecoder.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-messageDecoder.o `test -f 'src/cantomat/messageDecoder.c' || echo '$(srcdir)/'`src/cantomat/messageDecoder.c

src/cantomat/cantomat-messageDecoder.obj: src/cantomat/messageDecoder.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-messageDecoder.obj -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-messageDecoder.Tpo -c -o src/cantomat/cantomat-messageDecoder.obj `if test -f 'src/cantomat/messageDecoder.c'; then $(CYGPATH_W) 'src/cantomat/messageDecoder.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/messageDecoder.c'; fi`
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-messageDecoder.Tpo src/cantomat/$(DEPDIR)/cantomat-messageDecoder.Po
#	$(AM_V_CC)source='src/cantomat/messageDecoder.c' object='src/cantomat/cantomat-messageDecoder.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-messageDecoder.obj `if test -f 'src/cantomat/messageDecoder.c'; then $(CYGPATH_W) 'src/cantomat/messageDecoder.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/messageDecoder.c'; fi`

src/cantomat/cantomat-busAssignment.o: src/cantomat/busAssignment.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-busAssignment.o -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-busAssignment.Tpo -c -o src/cantomat/cantomat-busAssignment.o `test -f 'src/cantomat/busAssignment.c' || echo '$(srcdir)/'`src/cantomat/busAssignment.c
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-busAssignment.Tpo src/cantomat/$(DEPDIR)/cantomat-busAssignment.Po
#	$(AM_V_CC)source='src/cantomat/busAssignment.c' object='src/cantomat/cantomat-busAssignment.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-busAssignment.o `test -f 'src/cantomat/busAssignment.c' || echo '$(srcdir)/'`src/cantomat/busAssignment.c

src/cantomat/cantomat-busAssignment.obj: src/cantomat/busAssignment.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-busAssignment.obj -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-busAssignment.Tpo -c -o src/cantomat/cantomat-busAssignment.obj `if test -f 'src/cantomat/busAssignment.c'; then $(CYGPATH_W) 'src/cantomat/busAssignment.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/busAssignment.c'; fi`
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-busAssignment.Tpo src/cantomat/$(DEPDIR)/cantomat-busAssignment.Po
#	$(AM_V_CC)source='src/cantomat/busAssignment.c' object='src/cantomat/cantomat-busAssignment.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-busAssignment.obj `if test -f 'src/cantomat/busAssignment.c'; then $(CYGPATH_W) 'src/cantomat/busAssignment.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/busAssignment.c'; fi`

src/cantomat/cantomat-matWrite.o: src/cantomat/matWrite.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-matWrite.o -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-matWrite.Tpo -c -o src/cantomat/cantomat-matWrite.o `test -f 'src/cantomat/matWrite.c' || echo '$(srcdir)/'`src/cantomat/matWrite.c
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-matWrite.Tpo src/cantomat/$(DEPDIR)/cantomat-matWrite.Po
#	$(AM_V_CC)source='src/cantomat/matWrite.c' object='src/cantomat/cantomat-matWrite.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-matWrite.o `test -f 'src/cantomat/matWrite.c' || echo '$(srcdir)/'`src/cantomat/matWrite.c

src/cantomat/cantomat-matWrite.obj: src/cantomat/matWrite.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-matWrite.obj -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-matWrite.Tpo -c -o src/cantomat/cantomat-matWrite.obj `if test -f 'src/cantomat/matWrite.c'; then $(CYGPATH_W) 'src/cantomat/matWrite.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/matWrite.c'; fi`
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-matWrite.Tpo src/cantomat/$(DEPDIR)/cantomat-matWrite.Po
#	$(AM_V_CC)source='src/cantomat/matWrite.c' object='src/cantomat/cantomat-matWrite.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-matWrite.obj `if test -f 'src/cantomat/matWrite.c'; then $(CYGPATH_W) 'src/cantomat/matWrite.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/matWrite.c'; fi`

src/cantomat/cantomat-messageHash.o: src/cantomat/messageHash.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-messageHash.o -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-messageHash.Tpo -c -o src/cantomat/cantomat-messageHash.o `test -f 'src/cantomat/messageHash.c' || echo '$(srcdir)/'`src/cantomat/messageHash.c
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-messageHash.Tpo src/cantomat/$(DEPDIR)/cantomat-messageHash.Po
#	$(AM_V_CC)source='src/cantomat/messageHash.c' object='src/cantomat/cantomat-messageHash.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-messageHash.o `test -f 'src/cantomat/messageHash.c' || echo '$(srcdir)/'`src/cantomat/messageHash.c

src/cantomat/cantomat-messageHash.obj: src/cantomat/messageHash.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-messageHash.obj -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-messageHash.Tpo -c -o src/cantomat/cantomat-messageHash.obj `if test -f 'src/cantomat/messageHash.c'; then $(CYGPATH_W) 'src/cantomat/messageHash.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/messageHash.c'; fi`
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-messageHash.Tpo src/cantomat/$(DEPDIR)/cantomat-messageHash.Po
#	$(AM_V_CC)source='src/cantomat/messageHash.c' object='src/cantomat/cantomat-messageHash.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-messageHash.obj `if test -f 'src/cantomat/messageHash.c'; then $(CYGPATH_W) 'src/cantomat/messageHash.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/messageHash.c'; fi`

src/cantomat/cantomat-measurement.o: src/cantomat/measurement.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-measurement.o -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-measurement.Tpo -c -o src/cantomat/cantomat-measurement.o `test -f 'src/cantomat/measurement.c' || echo '$(srcdir)/'`src/cantomat/measurement.c
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-measurement.Tpo src/cantomat/$(DEPDIR)/cantomat-measurement.Po
#	$(AM_V_CC)source='src/cantomat/measurement.c' object='src/cantomat/cantomat-measurement.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-measurement.o `test -f 'src/cantomat/measurement.c' || echo '$(srcdir)/'`src/cantomat/measurement.c

src/cantomat/cantomat-measurement.obj: src/cantomat/measurement.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-measurement.obj -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-measurement.Tpo -c -o src/cantomat/cantomat-measurement.obj `if test -f 'src/cantomat/measurement.c'; then $(CYGPATH_W) 'src/cantomat/measurement.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/measurement.c'; fi`
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-measurement.Tpo src/cantomat/$(DEPDIR)/cantomat-measurement.Po
#	$(AM_V_CC)source='src/cantomat/measurement.c' object='src/cantomat/cantomat-measurement.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-measurement.obj `if test -f 'src/cantomat/measurement.c'; then $(CYGPATH_W) 'src/cantomat/measurement.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/measurement.c'; fi`

src/cantomat/cantomat-signalFormat.o: src/cantomat/signalFormat.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-signalFormat.o -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-signalFormat.Tpo -c -o src/cantomat/cantomat-signalFormat.o `test -f 'src/cantomat/signalFormat.c' || echo '$(srcdir)/'`src/cantomat/signalFormat.c
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-signalFormat.Tpo src/cantomat/$(DEPDIR)/cantomat-signalFormat.Po
#	$(AM_V_CC)source='src/cantomat/signalFormat.c' object='src/cantomat/cantomat-signalFormat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-signalFormat.o `test -f 'src/cantomat/signalFormat.c' || echo '$(srcdir)/'`src/cantomat/signalFormat.c

src/cantomat/cantomat-signalFormat.obj: src/cantomat/signalFormat.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/cantomat/cantomat-signalFormat.obj -MD -MP -MF src/cantomat/$(DEPDIR)/cantomat-signalFormat.Tpo -c -o src/cantomat/cantomat-signalFormat.obj `if test -f 'src/cantomat/signalFormat.c'; then $(CYGPATH_W) 'src/cantomat/signalFormat.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/signalFormat.c'; fi`
	$(AM_V_at)$(am__mv) src/cantomat/$(DEPDIR)/cantomat-signalFormat.Tpo src/cantomat/$(DEPDIR)/cantomat-signalFormat.Po
#	$(AM_V_CC)source='src/cantomat/signalFormat.c' object='src/cantomat/cantomat-signalFormat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/cantomat/cantomat-signalFormat.obj `if test -f 'src/cantomat/signalFormat.c'; then $(CYGPATH_W) 'src/cantomat/signalFormat.c'; else $(CYGPATH_W) '$(srcdir)/src/cantomat/signalFormat.c'; fi`

src/hashtable/cantomat-hashtable.o: src/hashtable/hashtable.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/hashtable/cantomat-hashtable.o -MD -MP -MF src/hashtable/$(DEPDIR)/cantomat-hashtable.Tpo -c -o src/hashtable/cantomat-hashtable.o `test -f 'src/hashtable/hashtable.c' || echo '$(srcdir)/'`src/hashtable/hashtable.c
	$(AM_V_at)$(am__mv) src/hashtable/$(DEPDIR)/cantomat-hashtable.Tpo src/hashtable/$(DEPDIR)/cantomat-hashtable.Po
#	$(AM_V_CC)source='src/hashtable/hashtable.c' object='src/hashtable/cantomat-hashtable.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/hashtable/cantomat-hashtable.o `test -f 'src/hashtable/hashtable.c' || echo '$(srcdir)/'`src/hashtable/hashtable.c

src/hashtable/cantomat-hashtable.obj: src/hashtable/hashtable.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/hashtable/cantomat-hashtable.obj -MD -MP -MF src/hashtable/$(DEPDIR)/cantomat-hashtable.Tpo -c -o src/hashtable/cantomat-hashtable.obj `if test -f 'src/hashtable/hashtable.c'; then $(CYGPATH_W) 'src/hashtable/hashtable.c'; else $(CYGPATH_W) '$(srcdir)/src/hashtable/hashtable.c'; fi`
	$(AM_V_at)$(am__mv) src/hashtable/$(DEPDIR)/cantomat-hashtable.Tpo src/hashtable/$(DEPDIR)/cantomat-hashtable.Po
#	$(AM_V_CC)source='src/hashtable/hashtable.c' object='src/hashtable/cantomat-hashtable.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/hashtable/cantomat-hashtable.obj `if test -f 'src/hashtable/hashtable.c'; then $(CYGPATH_W) 'src/hashtable/hashtable.c'; else $(CYGPATH_W) '$(srcdir)/src/hashtable/hashtable.c'; fi`

src/hashtable/cantomat-hashtable_itr.o: src/hashtable/hashtable_itr.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/hashtable/cantomat-hashtable_itr.o -MD -MP -MF src/hashtable/$(DEPDIR)/cantomat-hashtable_itr.Tpo -c -o src/hashtable/cantomat-hashtable_itr.o `test -f 'src/hashtable/hashtable_itr.c' || echo '$(srcdir)/'`src/hashtable/hashtable_itr.c
	$(AM_V_at)$(am__mv) src/hashtable/$(DEPDIR)/cantomat-hashtable_itr.Tpo src/hashtable/$(DEPDIR)/cantomat-hashtable_itr.Po
#	$(AM_V_CC)source='src/hashtable/hashtable_itr.c' object='src/hashtable/cantomat-hashtable_itr.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/hashtable/cantomat-hashtable_itr.o `test -f 'src/hashtable/hashtable_itr.c' || echo '$(srcdir)/'`src/hashtable/hashtable_itr.c

src/hashtable/cantomat-hashtable_itr.obj: src/hashtable/hashtable_itr.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/hashtable/cantomat-hashtable_itr.obj -MD -MP -MF src/hashtable/$(DEPDIR)/cantomat-hashtable_itr.Tpo -c -o src/hashtable/cantomat-hashtable_itr.obj `if test -f 'src/hashtable/hashtable_itr.c'; then $(CYGPATH_W) 'src/hashtable/hashtable_itr.c'; else $(CYGPATH_W) '$(srcdir)/src/hashtable/hashtable_itr.c'; fi`
	$(AM_V_at)$(am__mv) src/hashtable/$(DEPDIR)/cantomat-hashtable_itr.Tpo src/hashtable/$(DEPDIR)/cantomat-hashtable_itr.Po
#	$(AM_V_CC)source='src/hashtable/hashtable_itr.c' object='src/hashtable/cantomat-hashtable_itr.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(cantomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/hashtable/cantomat-hashtable_itr.obj `if test -f 'src/hashtable/hashtable_itr.c'; then $(CYGPATH_W) 'src/hashtable/hashtable_itr.c'; else $(CYGPATH_W) '$(srcdir)/src/hashtable/hashtable_itr.c'; fi`

src/dbccopy/dbccopy-dbccopy.o: src/dbccopy/dbccopy.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(dbccopy_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/dbccopy/dbccopy-dbccopy.o -MD -MP -MF src/dbccopy/$(DEPDIR)/dbccopy-dbccopy.Tpo -c -o src/dbccopy/dbccopy-dbccopy.o `test -f 'src/dbccopy/dbccopy.c' || echo '$(srcdir)/'`src/dbccopy/dbccopy.c
	$(AM_V_at)$(am__mv) src/dbccopy/$(DEPDIR)/dbccopy-dbccopy.Tpo src/dbccopy/$(DEPDIR)/dbccopy-dbccopy.Po
#	$(AM_V_CC)source='src/dbccopy/dbccopy.c' object='src/dbccopy/dbccopy-dbccopy.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(dbccopy_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/dbccopy/dbccopy-dbccopy.o `test -f 'src/dbccopy/dbccopy.c' || echo '$(srcdir)/'`src/dbccopy/dbccopy.c

src/dbccopy/dbccopy-dbccopy.obj: src/dbccopy/dbccopy.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(dbccopy_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/dbccopy/dbccopy-dbccopy.obj -MD -MP -MF src/dbccopy/$(DEPDIR)/dbccopy-dbccopy.Tpo -c -o src/dbccopy/dbccopy-dbccopy.obj `if test -f 'src/dbccopy/dbccopy.c'; then $(CYGPATH_W) 'src/dbccopy/dbccopy.c'; else $(CYGPATH_W) '$(srcdir)/src/dbccopy/dbccopy.c'; fi`
	$(AM_V_at)$(am__mv) src/dbccopy/$(DEPDIR)/dbccopy-dbccopy.Tpo src/dbccopy/$(DEPDIR)/dbccopy-dbccopy.Po
#	$(AM_V_CC)source='src/dbccopy/dbccopy.c' object='src/dbccopy/dbccopy-dbccopy.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(dbccopy_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/dbccopy/dbccopy-dbccopy.obj `if test -f 'src/dbccopy/dbccopy.c'; then $(CYGPATH_W) 'src/dbccopy/dbccopy.c'; else $(CYGPATH_W) '$(srcdir)/src/dbccopy/dbccopy.c'; fi`

src/dbcls/dbcls-dbcls.o: src/dbcls/dbcls.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(dbcls_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/dbcls/dbcls-dbcls.o -MD -MP -MF src/dbcls/$(DEPDIR)/dbcls-dbcls.Tpo -c -o src/dbcls/dbcls-dbcls.o `test -f 'src/dbcls/dbcls.c' || echo '$(srcdir)/'`src/dbcls/dbcls.c
	$(AM_V_at)$(am__mv) src/dbcls/$(DEPDIR)/dbcls-dbcls.Tpo src/dbcls/$(DEPDIR)/dbcls-dbcls.Po
#	$(AM_V_CC)source='src/dbcls/dbcls.c' object='src/dbcls/dbcls-dbcls.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(dbcls_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/dbcls/dbcls-dbcls.o `test -f 'src/dbcls/dbcls.c' || echo '$(srcdir)/'`src/dbcls/dbcls.c

src/dbcls/dbcls-dbcls.obj: src/dbcls/dbcls.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(dbcls_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/dbcls/dbcls-dbcls.obj -MD -MP -MF src/dbcls/$(DEPDIR)/dbcls-dbcls.Tpo -c -o src/dbcls/dbcls-dbcls.obj `if test -f 'src/dbcls/dbcls.c'; then $(CYGPATH_W) 'src/dbcls/dbcls.c'; else $(CYGPATH_W) '$(srcdir)/src/dbcls/dbcls.c'; fi`
	$(AM_V_at)$(am__mv) src/dbcls/$(DEPDIR)/dbcls-dbcls.Tpo src/dbcls/$(DEPDIR)/dbcls-dbcls.Po
#	$(AM_V_CC)source='src/dbcls/dbcls.c' object='src/dbcls/dbcls-dbcls.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(dbcls_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/dbcls/dbcls-dbcls.obj `if test -f 'src/dbcls/dbcls.c'; then $(CYGPATH_W) 'src/dbcls/dbcls.c'; else $(CYGPATH_W) '$(srcdir)/src/dbcls/dbcls.c'; fi`

src/matdump/matdump-matdump.o: src/matdump/matdump.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(matdump_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/matdump/matdump-matdump.o -MD -MP -MF src/matdump/$(DEPDIR)/matdump-matdump.Tpo -c -o src/matdump/matdump-matdump.o `test -f 'src/matdump/matdump.c' || echo '$(srcdir)/'`src/matdump/matdump.c
	$(AM_V_at)$(am__mv) src/matdump/$(DEPDIR)/matdump-matdump.Tpo src/matdump/$(DEPDIR)/matdump-matdump.Po
#	$(AM_V_CC)source='src/matdump/matdump.c' object='src/matdump/matdump-matdump.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(matdump_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/matdump/matdump-matdump.o `test -f 'src/matdump/matdump.c' || echo '$(srcdir)/'`src/matdump/matdump.c

src/matdump/matdump-matdump.obj: src/matdump/matdump.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(matdump_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/matdump/matdump-matdump.obj -MD -MP -MF src/matdump/$(DEPDIR)/matdump-matdump.Tpo -c -o src/matdump/matdump-matdump.obj `if test -f 'src/matdump/matdump.c'; then $(CYGPATH_W) 'src/matdump/matdump.c'; else $(CYGPATH_W) '$(srcdir)/src/matdump/matdump.c'; fi`
	$(AM_V_at)$(am__mv) src/matdump/$(DEPDIR)/matdump-matdump.Tpo src/matdump/$(DEPDIR)/matdump-matdump.Po
#	$(AM_V_CC)source='src/matdump/matdump.c' object='src/matdump/matdump-matdump.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(matdump_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/matdump/matdump-matdump.obj `if test -f 'src/matdump/matdump.c'; then $(CYGPATH_W) 'src/matdump/matdump.c'; else $(CYGPATH_W) '$(srcdir)/src/matdump/matdump.c'; fi`

src/mdftomat/mdftomat-mdftomat.o: src/mdftomat/mdftomat.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mdftomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/mdftomat/mdftomat-mdftomat.o -MD -MP -MF src/mdftomat/$(DEPDIR)/mdftomat-mdftomat.Tpo -c -o src/mdftomat/mdftomat-mdftomat.o `test -f 'src/mdftomat/mdftomat.c' || echo '$(srcdir)/'`src/mdftomat/mdftomat.c
	$(AM_V_at)$(am__mv) src/mdftomat/$(DEPDIR)/mdftomat-mdftomat.Tpo src/mdftomat/$(DEPDIR)/mdftomat-mdftomat.Po
#	$(AM_V_CC)source='src/mdftomat/mdftomat.c' object='src/mdftomat/mdftomat-mdftomat.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mdftomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/mdftomat/mdftomat-mdftomat.o `test -f 'src/mdftomat/mdftomat.c' || echo '$(srcdir)/'`src/mdftomat/mdftomat.c

src/mdftomat/mdftomat-mdftomat.obj: src/mdftomat/mdftomat.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mdftomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT src/mdftomat/mdftomat-mdftomat.obj -MD -MP -MF src/mdftomat/$(DEPDIR)/mdftomat-mdftomat.Tpo -c -o src/mdftomat/mdftomat-mdftomat.obj `if test -f 'src/mdftomat/mdftomat.c'; then $(CYGPATH_W) 'src/mdftomat/mdftomat.c'; else $(CYGPATH_W) '$(srcdir)/src/mdftomat/mdftomat.c'; fi`
	$(AM_V_at)$(am__mv) src/mdftomat/$(DEPDIR)/mdftomat-mdftomat.Tpo src/mdftomat/$(DEPDIR)/mdftomat-mdftomat.Po
#	$(AM_V_CC)source='src/mdftomat/mdftomat.c' object='src/mdftomat/mdftomat-mdftomat.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(mdftomat_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o src/mdftomat/mdftomat-mdftomat.obj `if test -f 'src/mdftomat/mdftomat.c'; then $(CYGPATH_W) 'src/mdftomat/mdftomat.c'; else $(CYGPATH_W) '$(srcdir)/src/mdftomat/mdftomat.c'; fi`

.l.c:
	$(AM_V_LEX)$(am__skiplex) $(SHELL) $(YLWRAP) $< $(LEX_OUTPUT_ROOT).c $@ -- $(LEXCOMPILE)

.y.c:
	$(AM_V_YACC)$(am__skipyacc) $(SHELL) $(YLWRAP) $< y.tab.c $@ y.tab.h `echo $@ | $(am__yacc_c2h)` y.output $*.output -- $(YACCCOMPILE)

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf src/libcanasc/.libs src/libcanasc/_libs
	-rm -rf src/libcanclg/.libs src/libcanclg/_libs
	-rm -rf src/libcandbc/.libs src/libcandbc/_libs
	-rm -rf src/libcanmdf/.libs src/libcanmdf/_libs
	-rm -rf src/libcanvsb/.libs src/libcanvsb/_libs

distclean-libtool:
	-rm -f libtool config.lt
install-includeHEADERS: $(include_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(include_HEADERS)'; test -n "$(includedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(includedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(includedir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(includedir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(includedir)" || exit $$?; \
	done

uninstall-includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(include_HEADERS)'; test -n "$(includedir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(includedir)'; $(am__uninstall_files_from_dir)

# This directory's subdirectories are mostly independent; you can cd
# into them and run 'make' without going through this Makefile.
# To change the values of 'make' variables: instead of editing Makefiles,
# (1) if the variable is set in 'config.status', edit 'config.status'
#     (which will cause the Makefiles to be regenerated when you run 'make');
# (2) otherwise, pass the desired values on the 'make' command line.
$(am__recursive_targets):
	@fail=; \
	if $(am__make_keepgoing); then \
	  failcom='fail=yes'; \
	else \
	  failcom='exit 1'; \
	fi; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  ($(am__cd) $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-recursive
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      set "$$@" "$$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-recursive

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-recursive

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	@list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    $(am__make_dryrun) \
	      || test -d "$(distdir)/$$subdir" \
	      || $(MKDIR_P) "$(distdir)/$$subdir" \
	      || exit 1; \
	    dir1=$$subdir; dir2="$(distdir)/$$subdir"; \
	    $(am__relativize); \
	    new_distdir=$$reldir; \
	    dir1=$$subdir; dir2="$(top_distdir)"; \
	    $(am__relativize); \
	    new_top_distdir=$$reldir; \
	    echo " (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir="$$new_top_distdir" distdir="$$new_distdir" \\"; \
	    echo "     am__remove_distdir=: am__skip_length_check=: am__skip_mode_fix=: distdir)"; \
	    ($(am__cd) $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$new_top_distdir" \
	        distdir="$$new_distdir" \
		am__remove_distdir=: \
		am__skip_length_check=: \
		am__skip_mode_fix=: \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(HEADERS) config.h
install-binPROGRAMS: install-libLTLIBRARIES

installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(includedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f src/cantomat/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/cantomat/$(am__dirstamp)
	-rm -f src/dbccopy/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/dbccopy/$(am__dirstamp)
	-rm -f src/dbcls/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/dbcls/$(am__dirstamp)
	-rm -f src/hashtable/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/hashtable/$(am__dirstamp)
	-rm -f src/libcanasc/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/libcanasc/$(am__dirstamp)
	-rm -f src/libcanclg/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/libcanclg/$(am__dirstamp)
	-rm -f src/libcandbc/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/libcandbc/$(am__dirstamp)
	-rm -f src/libcanmdf/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/libcanmdf/$(am__dirstamp)
	-rm -f src/libcanvsb/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/libcanvsb/$(am__dirstamp)
	-rm -f src/matdump/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/matdump/$(am__dirstamp)
	-rm -f src/mdftomat/$(DEPDIR)/$(am__dirstamp)
	-rm -f src/mdftomat/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-rm -f src/libcandbc/lexer.c
	-rm -f src/libcandbc/parser.c
	-rm -f src/libcandbc/parser.h
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(DEPDIR) src/cantomat/$(DEPDIR) src/dbccopy/$(DEPDIR) src/dbcls/$(DEPDIR) src/hashtable/$(DEPDIR) src/libcanasc/$(DEPDIR) src/libcanclg/$(DEPDIR) src/libcandbc/$(DEPDIR) src/libcanmdf/$(DEPDIR) src/libcanvsb/$(DEPDIR) src/matdump/$(DEPDIR) src/mdftomat/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

html-am:

info: info-recursive

info-am:

install-data-am: install-includeHEADERS

install-dvi: install-dvi-recursive

install-dvi-am:

install-exec-am: install-binPROGRAMS install-libLTLIBRARIES
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook
install-html: install-html-recursive

install-html-am:

install-info: install-info-recursive

install-info-am:

install-man:

install-pdf: install-pdf-recursive

install-pdf-am:

install-ps: install-ps-recursive

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf $(DEPDIR) src/cantomat/$(DEPDIR) src/dbccopy/$(DEPDIR) src/dbcls/$(DEPDIR) src/hashtable/$(DEPDIR) src/libcanasc/$(DEPDIR) src/libcanclg/$(DEPDIR) src/libcandbc/$(DEPDIR) src/libcanmdf/$(DEPDIR) src/libcanvsb/$(DEPDIR) src/matdump/$(DEPDIR) src/mdftomat/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-includeHEADERS \
	uninstall-libLTLIBRARIES

.MAKE: $(am__recursive_targets) all install-am install-exec-am \
	install-strip

.PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am \
	am--refresh check check-am clean clean-binPROGRAMS \
	clean-cscope clean-generic clean-libLTLIBRARIES clean-libtool \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-exec-hook install-html install-html-am \
	install-includeHEADERS install-info install-info-am \
	install-libLTLIBRARIES install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs installdirs-am maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-includeHEADERS uninstall-libLTLIBRARIES


src/libcandbc/parser.h src/libcandbc/parser.c: src/libcandbc/parser.y

install-exec-hook:
	cd $(DESTDIR)$(bindir) && \
		$(LN_S) cantomat$(EXEEXT) asctomat$(EXEEXT)
	cd $(DESTDIR)$(bindir) && \
		$(LN_S) cantomat$(EXEEXT) vsbtomat$(EXEEXT)
	cd $(DESTDIR)$(bindir) && \
		$(LN_S) cantomat$(EXEEXT) clgtomat$(EXEEXT)

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
